### ISSUE TITLE
not all defaults are rendered

### ISSUE THREAD

**Issue by haarchri** [Skarlso/crd-to-sample-yaml#103]
when executing 

```
./cty generate -u https://raw.githubusercontent.com/crossplane-contrib/function-go-templating/main/package/input/gotemplating.fn.crossplane.io_gotemplates.yaml 
```

the result looks like:
```
apiVersion: gotemplating.fn.crossplane.io/v1beta1
delims:
  left: string
  right: "}}"
fileSystem:
  dirPath: string
inline:
  template: string
kind: GoTemplate
metadata: {}
source: string
```

i wonder why left is without the default value 
```
apiVersion: gotemplating.fn.crossplane.io/v1beta1
delims:
  left: "{{"
  right: "}}"
fileSystem:
  dirPath: string
inline:
  template: string
kind: GoTemplate
metadata: {}
source: string

```
