### ISSUE TITLE
Idea/FeatureRequest: HTML - Grouping Resources by API Group with Descriptions

### ISSUE THREAD

**Issue by markussiebert** [Skarlso/crd-to-sample-yaml#126]
Firstly, thank you again for creating `cty` :-)

In this Szenario I use it to generate HTML documentation from a folder of CRDs.

To improve the user experience further, especially for end-users who have to navigate through numerous CRDs, it would be helpful to introduce a feature that allows the grouping of resources by their API Group in the documentation

### Grouping by Groups

It would be incredibly beneficial if cty could automatically group the resources by their apiGroup within the output html documentation. This would help provide thematic differentiation based on API groups (e.g., com.aws.services, com.azure.services, etc.).

### Descriptions for Groups

An even more user-friendly enhancement would be to allow custom descriptions for each of these groups. This additional context will help end-users understand the purpose and scope of each group better.

### Potential Implementation

- **Configuration File**: Support for an additional configuration file that contains these group descriptions. The file could be structured in a way where each API group can have a brief description assigned to it.
  
  Example format:
  ```yaml
  apiGroups:
    - name: "com.aws.services"
      description: "Resources related to AWS services"
    - name: "com.azure.services"
      description: "Resources related to Azure services"

**Comment by Skarlso** [comment]
Hello. Thanks for the idea! :) 

> Grouping by Kind

I believe this is already happening right? The versions are groupped under their KIND:
<img width="490" alt="Screenshot 2024-10-17 at 22 19 51" src="https://github.com/user-attachments/assets/fb89ba27-6902-40af-ba2c-466ee095bf18">

I like the idea of a potential configuration file though. :)

**Comment by markussiebert** [comment]
of course you are right - I thought of ApiGroups, but wrote Kind

**Comment by Skarlso** [comment]
So basically if you would have multiple things under the AWS api group those would be grouped by the API group such as, AWSCluster and Infrastructure or something and then inside that would be multiple kind groups for versions,

Is that correct?

**Comment by Skarlso** [comment]
Would something like this be okay?

```yaml
apiGroups:
  - name: "com.aws.services"
    description: "Resources related to AWS services"
    files: # files and folders can be defined together or on their own
      - aws1_crd.yaml
      - aws2_crd.yaml
    folders: # everything under this folder would be put under the configured category
      - aws1
      - aws2
  - name: "com.azure.services"
    description: "Resources related to Azure services"
    files:
      - azure1_crd.yaml
      - azure2_crd.yaml
```

This would help a lot in creating the right groups and all. If a configuration file is not defined, then we would just fall back on `kind` for groupping.
