### ISSUE TITLE
Feature request: support enums in API

### ISSUE THREAD

**Issue by Sijoma** [Skarlso/crd-to-sample-yaml#138]
I have an CRD that has the following OpenAPI field in the .spec :
```
              suspendStrategy:
                default: ScaleDown
                description: SuspendStrategy can be used to modify the behaviour that
                  is used when setting suspend to true.
                enum:
                - ScaleDown
                - ScaleDownAndDeleteDisk
                type: string
```

Its rendered like this:
<img width="903" alt="image" src="https://github.com/user-attachments/assets/a29fd5d5-e8e0-4ebe-93b6-11ca96ed8611">

Would it be possible instead of only showing "string", that the two possible values are displayed somewhere?
