### ISSUE TITLE
map[string]string is not recognised

### ISSUE THREAD

**Issue by Callisto13** [Skarlso/crd-to-sample-yaml#14]
Check out these renderings: https://weaveworks-liquidmetal.github.io/site/docs/guides/capmvm/#capmvm-api

`metadata`, `failureDomains`, `kernelCmdKine` etc are all `map[string]string`.

I would imaging all `map`s do not get translated

**Comment by Skarlso** [comment]
Huh. Good catch! :)

**Comment by Skarlso** [comment]
Ah! I see. Because for those, it's `additionalProperties` instead of `properties` :D "Clever. :D

**Comment by Skarlso** [comment]
Fixed, but there are limits to it. For example:

```yaml
                    securityGroupOverrides:
                      additionalProperties:
                        type: string
                      description: SecurityGroupOverrides is an optional set of security
                        groups to use for cluster instances This is optional - if not
                        provided new security groups will be created for the cluster
                      type: object
```

Things like these will appear like this:

```yaml
        fromPort: 1
        protocol: string
        toPort: 1
    securityGroupOverrides:
    subnets:
```

Not entirely sure yet what I can put there. 🤷

**Comment by Skarlso** [comment]
Fixed the latest release. If you are happy with the above @Callisto13 we can close this for now. There might be others missing as well. 🤔 I have to experiment a bit. :)

**Comment by Callisto13** [comment]
hmmmm 

```yaml
foobar:
```

is somehow less clear than:

```yaml
foobar: {}
```

🤔

**Comment by Skarlso** [comment]
Yah... I have to.. um... figure out some default value there. 🤔 

But at least, now it's rendering a bunch of stuff it hasn't before hahahaha. :D

**Comment by Callisto13** [comment]
true true 😄

**Comment by Skarlso** [comment]
@Skarlso I'll try to bring back that `{}` instead. This is really a bit confusing to look at.

**Comment by Skarlso** [comment]
Object that don't have any additional properties but are themselves objects, like `additionalTags` here:

```yaml
              properties:
                additionalTags:
                  additionalProperties:
                    type: string
                  description: AdditionalTags is an optional set of tags to add to AWS
                    resources managed by the AWS provider, in addition to the ones added
                    by default.
                  type: object
```

Are rendered like this:

```yaml
  additionalTags: {}
```
