### ISSUE TITLE
If description is available, put that into the yaml file as comment

### ISSUE THREAD

**Issue by Skarlso** [Skarlso/crd-to-sample-yaml#35]
You should be able to turn this feature off.

**Comment by Skarlso** [comment]
Not going to do this because it makes the YAML super ugly.

```yaml
    # Configuration options for the root storage volume.
    rootVolume:
      # Device name
      deviceName: string
      # Encrypted is whether the volume should be encrypted or not.
      encrypted: true
      # EncryptionKey is the KMS key to use to encrypt the volume. Can be either a KMS key ID or ARN. If Encrypted is set and this is omitted, the default AWS key will be used. The key must already exist and be accessible by the controller.
      encryptionKey: string
      # IOPS is the number of IOPS requested for the disk. Not applicable to all types.
      iops: 1
      # Size specifies size (in Gi) of the storage device. Must be greater than the image snapshot size or 8 (whichever is greater).
      size: 1
      # Throughput to provision in MiB/s supported for the volume type. Not applicable to all types.
      throughput: 1
      # Type is the type of the volume (e.g. gp2, io1, etc...).
      type: string
    # SecurityGroupIDs are one or more security group IDs this instance belongs to.
    securityGroupIds: ["string"]
    # SpotMarketOptions option for configuring instances to be run using AWS Spot instances.
    spotMarketOptions:
      # MaxPrice defines the maximum price the user is willing to pay for Spot VM instances
      maxPrice: string
    # The name of the SSH key pair.
    sshKeyName: string
    # The ID of the subnet of the instance.
    subnetId: string
    # The tags associated with the instance.
    tags: {}
    # Tenancy indicates if instance should run on shared or single-tenant hardware.
    tenancy: string
    # The instance type.
    type: string
    # UserData is the raw data script passed to the instance which is run upon bootstrap. This field must not be base64 encoded and should only be used when running a new instance.
    userData: string
    # IDs of the instance's volumes
    volumeIDs: ["string"]
```
