### ISSUE TITLE
bug: minimal example lacks required metadata

### ISSUE THREAD

**Issue by markussiebert** [Skarlso/crd-to-sample-yaml#75]
Hi, sorry, I didn't saw it yesterday - was late:

```yaml
apiVersion: cdaas.dp.db.de/v1alpha1
kind: KubernetesAgent
# All information for the provider
spec:
...
```

The minimal example lacks the required metadata XD. Even if it's not marked as required, name and namespace should be present.
