### ISSUE TITLE
feat: URL to CRDs definition will ignore go-template blocks

### ISSUE THREAD

**Issue by lzima** [Skarlso/crd-to-sample-yaml#84]
Hi, 

in helm chart templates, there are usually go-template functions or blocks, and I wish to point to the CRDs definition with go-template blocks and render yaml from this file.

for example: 
https://raw.githubusercontent.com/fluxcd-community/helm-charts/main/charts/flux2/templates/helm-controller.crds.yaml
```yaml
{{- if and .Values.installCRDs .Values.helmController.create }}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.15.0
  labels:
    app.kubernetes.io/component: helm-controller
...
...
...
    subresources:
      status: {}
{{- end }}
```

Now I getting error in UI
<img width="1339" alt="image" src="https://github.com/Skarlso/crd-to-sample-yaml/assets/133737201/bc779e95-671c-4fbb-9067-227745a575f7">
<img width="921" alt="image" src="https://github.com/Skarlso/crd-to-sample-yaml/assets/133737201/4acf268c-7a02-40e0-b023-445501c632d0">
